// Known listing IDs that exist on the contract
// This list was generated by checking listings 1-1233 individually
// Last updated: Checked all listings from 1 to 1233

export const KNOWN_LISTING_IDS = [
  10, 25, 229, 551, 564, 854, 927, 929, 930, 931, 942, 943, 947, 948, 952, 960, 963, 965, 967, 968,
  973, 974, 975, 976, 978, 980, 984, 985, 986, 987, 993, 996, 1001, 1005, 1008, 1022, 1027, 1029,
  1032, 1035, 1036, 1040, 1045, 1048, 1050, 1051, 1054, 1058, 1062, 1064, 1065, 1067, 1068, 1069,
  1075, 1076, 1077, 1080, 1083, 1086, 1087, 1090, 1093, 1094, 1099, 1100, 1102, 1110, 1111, 1113,
  1115, 1131, 1139, 1144, 1146, 1147, 1148, 1159, 1161, 1163, 1164, 1165, 1166, 1167, 1170, 1171,
  1172, 1173, 1174, 1175, 1176, 1177, 1178, 1179, 1180, 1181, 1182, 1183, 1184, 1185, 1186, 1187,
  1188, 1189, 1190, 1191, 1192, 1193, 1194, 1195, 1196, 1197, 1198, 1199, 1200, 1202, 1204, 1207,
  1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1226, 1227, 1229, 1233
] as const;

// Last checked listing ID - check for new listings after this
export const LAST_CHECKED_LISTING_ID = 1233;

// Get all listing IDs to check (known + potential new ones after last checked)
export function getListingIDsToCheck(nextListingId: number): number[] {
  const knownIds = [...KNOWN_LISTING_IDS];
  const newIds: number[] = [];
  
  // Check for new listings after the last checked ID
  if (nextListingId > LAST_CHECKED_LISTING_ID) {
    for (let id = LAST_CHECKED_LISTING_ID + 1; id < nextListingId; id++) {
      newIds.push(id);
    }
  }
  
  return [...knownIds, ...newIds];
}
